
@ArtifactsAPI_HostAddress = https://localhost:7066
// Note: If this token expires, run the `POST /api/Auth/login` endpoint below to generate a new one, then replace this token.
@MyToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJIb3NzYW0iLCJlbWFpbCI6Imhvc3NhbUBlbmdpbmVlci5jb20iLCJyb2xlIjoiRW5naW5lZXIiLCJuYmYiOjE3NzY2Mzg4OTUsImV4cCI6MTc3NzI0MzY5NSwiaWF0IjoxNzc2NjM4ODk1LCJpc3MiOiJBcnRpZmFjdHNBUEkiLCJhdWQiOiJGbHV0dGVyQXBwVXNlcnMifQ.jvx4ZDFoB2Y5RZA-xrLCp0GlEdFi9dWDXfB12kxoOAA

### 
POST {{ArtifactsAPI_HostAddress}}/api/Artifacts
Content-Type: application/json
Authorization: Bearer {{MyToken}}

{
  "name": "King Hossam Mask",
  "history": "Found in Valley of the Kings by Howard Carter in 1922.",
  "location": "Grand Egyptian Museum"
}

### 2.
POST {{ArtifactsAPI_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "name": "Hossam",
  "email": "hossam@engineer.com",
  "role": "Engineer",
  "passwordHash": "Password123" 
}

### 3. 
POST {{ArtifactsAPI_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "hossam@engineer.com",
  "passwordHash": "Password123" 
}



### 5. 
GET {{ArtifactsAPI_HostAddress}}/api/Artifacts
Authorization: Bearer {{MyToken}}
Accept: application/json





### Create a New Post (With Coordinates)
POST {{ArtifactsAPI_HostAddress}}/api/Posts
Content-Type: application/json
Authorization: Bearer {{MyToken}}

{
  "title": "The Great Sphinx Scan",
  "description": "A detailed 3D scan of the Sphinx",
  "coverPhoto": "https://url.com/cover.jpg",
  "model3D": "https://url.com/model.glb",
  "coordinates": [
    {
      "title": "Head Position",
      "description": "Right eye area",
      "x": 29.9753,
      "y": 31.1308
    },
    {
      "title": "Base Position",
      "description": "Left paw area",
      "x": 29.9750,
      "y": 31.1305
    }
  ]
}

### Get All Posts
GET {{ArtifactsAPI_HostAddress}}/api/Posts
Accept: application/json