@ArtifactsAPI_HostAddress = https://localhost:7066

### 
POST {{ArtifactsAPI_HostAddress}}/api/Artifacts
Content-Type: application/json

{
  "name": "King Tut Mask",
  "history": "Found in Valley of the Kings by Howard Carter in 1922.",
  "location": "Grand Egyptian Museum"
}

### (Register)
POST {{ArtifactsAPI_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "name": "Hossam",
  "email": "hossam@engineer.com",
  "role": "Engineer",
  "passwordHash": "Password123" 
}
### 3.  (Login)
POST {{ArtifactsAPI_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "hossam@engineer.com",
  "passwordHash": "Password123" 
}

### 4. 
GET {{ArtifactsAPI_HostAddress}}/api/Artifacts
Accept: application/json